In [1]:
s3.ls('tt-bootcamp-shared')

['tt-bootcamp-shared/hackernews.parquet',
 'tt-bootcamp-shared/nyc-bike-trip',
 'tt-bootcamp-shared/nyc-taxi-trip',
 'tt-bootcamp-shared/tips.csv',
 'tt-bootcamp-shared/titanic.csv']

In [9]:
%%duckdb

select * from 's3://tt-bootcamp-shared/titanic.csv' 
WHERE age < 10 and sex='female' and not alive
order by age
limit 10

,column00,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,642,0,3,female,2.0,3,2,27.9000,S,Third,child,False,None,Southampton,False,False
1,297,0,1,female,2.0,1,2,151.5500,S,First,child,False,C,Southampton,False,False
2,119,0,3,female,2.0,4,2,31.2750,S,Third,child,False,None,Southampton,False,False
3,205,0,3,female,2.0,0,1,10.4625,S,Third,child,False,G,Southampton,False,False
4,374,0,3,female,3.0,3,1,21.0750,S,Third,child,False,None,Southampton,False,False
5,813,0,3,female,6.0,4,2,31.2750,S,Third,child,False,None,Southampton,False,False
6,24,0,3,female,8.0,3,1,21.0750,S,Third,child,False,None,Southampton,False,False
7,147,0,3,female,9.0,2,2,34.3750,S,Third,child,False,None,Southampton,False,False
8,634,0,3,female,9.0,3,2,27.9000,S,Third,child,False,None,Southampton,False,False
9,541,0,3,female,9.0,4,2,31.2750,S,Third,child,False,None,Southampton,False,False

In [18]:
%%duckdb

select title,url,regexp_extract(url,'http[s]?://([^/]+)',1) as dom  from 's3://tt-bootcamp-shared/hackernews.parquet' 
where url is not null
limit 10

,title,url,dom
0,What Arc should learn from Ruby,http://antoniocangiano.com/2008/10/26/what-arc...,antoniocangiano.com
1,How to make your own spectrometer from a CD an...,http://www.cs.cmu.edu/~zhuxj/astro/html/spectr...,www.cs.cmu.edu
2,Free Samples : Free Stuff : Freebies,http://www.freestufffriend.com,www.freestufffriend.com
3,Great Source for Astrology,http://www.astrology-signs.org/,www.astrology-signs.org
4,Shuttleworth - GNOME usability hackfest,http://www.markshuttleworth.com/archives/223,www.markshuttleworth.com
5,Philip Greenspun: Race prejudice versus age pr...,http://blogs.law.harvard.edu/philg/2008/10/25/...,blogs.law.harvard.edu
6,Invent Now - Promoting Inventing to Kids,http://www.inventnow.org/,www.inventnow.org
7,US Army warns of Twitter dangers,http://www.breitbart.com/article.php?id=081025...,www.breitbart.com
8,The Toilet: Our Greatest Health Breakthrough E...,http://www.alternet.org/healthwellness/103995/...,www.alternet.org
9,Stop Home Foreclosure,http://www.stop-foreclosure-help.org/,www.stop-foreclosure-help.org

In [21]:
%%duckdb

select regexp_extract(url,'http[s]?://([^/]+)',1) as dom
      ,count(1) n  from 's3://tt-bootcamp-shared/hackernews.parquet' 
where url is not null
group by 1
order by 2 desc
limit 10

                  dom     n
0          medium.com  3349
1          github.com  2991
2     www.nytimes.com  2448
3     www.youtube.com  2256
4  www.techcrunch.com  1755
5      techcrunch.com  1292
6     arstechnica.com  1179
7       www.wired.com   820
8     venturebeat.com   744
9    en.wikipedia.org   725

In [23]:
s3.ls('tt-bootcamp-shared/nyc-taxi-trip/yellow-taxi-data')

['tt-bootcamp-shared/nyc-taxi-trip/yellow-taxi-data/yellow_tripdata_2024-10.parquet',
 'tt-bootcamp-shared/nyc-taxi-trip/yellow-taxi-data/yellow_tripdata_2024-11.parquet',
 'tt-bootcamp-shared/nyc-taxi-trip/yellow-taxi-data/yellow_tripdata_2024-12.parquet',
 'tt-bootcamp-shared/nyc-taxi-trip/yellow-taxi-data/yellow_tripdata_2025-01.parquet',
 'tt-bootcamp-shared/nyc-taxi-trip/yellow-taxi-data/yellow_tripdata_2025-02.parquet',
 'tt-bootcamp-shared/nyc-taxi-trip/yellow-taxi-data/yellow_tripdata_2025-03.parquet',
 'tt-bootcamp-shared/nyc-taxi-trip/yellow-taxi-data/yellow_tripdata_2025-04.parquet',
 'tt-bootcamp-shared/nyc-taxi-trip/yellow-taxi-data/yellow_tripdata_2025-05.parquet',
 'tt-bootcamp-shared/nyc-taxi-trip/yellow-taxi-data/yellow_tripdata_2025-06.parquet',
 'tt-bootcamp-shared/nyc-taxi-trip/yellow-taxi-data/yellow_tripdata_2025-07.parquet',
 'tt-bootcamp-shared/nyc-taxi-trip/yellow-taxi-data/yellow_tripdata_2025-08.parquet',
 'tt-bootcamp-shared/nyc-taxi-trip/yellow-taxi-data/yellow_tripdata_2025-09.parquet',
 'tt-bootcamp-shared/nyc-taxi-trip/yellow-taxi-data/yellow_tripdata_2025-10.parquet',
 'tt-bootcamp-shared/nyc-taxi-trip/yellow-taxi-data/yellow_tripdata_2025-11.parquet',
 'tt-bootcamp-shared/nyc-taxi-trip/yellow-taxi-data/yellow_tripdata_2025-12.parquet',
 'tt-bootcamp-shared/nyc-taxi-trip/yellow-taxi-data/yellow_tripdata_2026-01.parquet',
 'tt-bootcamp-shared/nyc-taxi-trip/yellow-taxi-data/yellow_tripdata_2026-02.parquet',
 'tt-bootcamp-shared/nyc-taxi-trip/yellow-taxi-data/yellow_tripdata_2026-03.parquet']

In [24]:
%%duckdb

select * from 's3://tt-bootcamp-shared/nyc-taxi-trip/yellow-taxi-data/*.parquet' limit 10

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,2,2024-10-01 00:30:44,2024-10-01 00:48:26,1,3.00,1,N,162,246,1,18.4,1.0,0.5,1.50,0.0,1.0,24.90,2.5,0.0
1,1,2024-10-01 00:12:20,2024-10-01 00:25:25,1,2.20,1,N,48,236,1,14.2,3.5,0.5,3.80,0.0,1.0,23.00,2.5,0.0
2,1,2024-10-01 00:04:46,2024-10-01 00:13:52,1,2.70,1,N,142,24,1,13.5,3.5,0.5,3.70,0.0,1.0,22.20,2.5,0.0
3,1,2024-10-01 00:12:10,2024-10-01 00:23:01,1,3.10,1,N,233,75,1,14.2,3.5,0.5,2.00,0.0,1.0,21.20,2.5,0.0
4,1,2024-10-01 00:30:22,2024-10-01 00:30:39,1,0.00,1,N,262,262,3,3.0,3.5,0.5,0.00,0.0,1.0,8.00,2.5,0.0
5,2,2024-10-01 00:31:20,2024-10-01 00:36:00,2,0.97,1,N,137,137,1,7.2,1.0,0.5,2.44,0.0,1.0,14.64,2.5,0.0
6,1,2024-10-01 00:42:57,2024-10-01 00:49:01,1,1.30,1,N,142,48,1,7.9,3.5,0.5,2.55,0.0,1.0,15.45,2.5,0.0
7,1,2024-10-01 00:59:55,2024-10-01 01:02:24,1,0.50,1,N,230,161,1,5.1,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0
8,1,2024-10-01 00:00:47,2024-10-01 00:04:22,0,1.10,1,N,142,237,1,7.2,3.5,0.5,3.00,0.0,1.0,15.20,2.5,0.0
9,1,2024-10-01 00:17:36,2024-10-01 00:26:22,1,2.20,1,N,162,145,1,11.4,3.5,0.5,3.30,0.0,1.0,19.70,2.5,0.0

In [30]:
%%duckdb

CREATE OR REPLACE MACRO calc_total(bill, tip) as bill + tip;
select * EXCLUDE(column0), calc_total(total_bill, tip) as subtotal from 's3://tt-bootcamp-shared/tips.csv'

     total_bill   tip     sex  smoker   day    time  size  subtotal
0         16.99  1.01  Female   False   Sun  Dinner     2     18.00
1         10.34  1.66    Male   False   Sun  Dinner     3     12.00
2         21.01  3.50    Male   False   Sun  Dinner     3     24.51
3         23.68  3.31    Male   False   Sun  Dinner     2     26.99
4         24.59  3.61  Female   False   Sun  Dinner     4     28.20
..          ...   ...     ...     ...   ...     ...   ...       ...
239       29.03  5.92    Male   False   Sat  Dinner     3     34.95
240       27.18  2.00  Female    True   Sat  Dinner     2     29.18
241       22.67  2.00    Male    True   Sat  Dinner     2     24.67
242       17.82  1.75    Male   False   Sat  Dinner     2     19.57
243       18.78  3.00  Female   False  Thur  Dinner     2     21.78

[244 rows x 8 columns]

In [36]:
%%duckdb


CREATE OR REPLACE MACRO is_adult(age, adult_age:=18) AS age >= adult_age;

select * from 's3://tt-bootcamp-shared/titanic.csv' 
WHERE is_adult(age)
order by age
limit 10

,column00,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,144,0,2,male,18.0,0,0,11.5000,S,Second,man,True,None,Southampton,False,True
1,228,0,2,male,18.0,0,0,13.0000,S,Second,man,True,None,Southampton,False,True
2,204,1,3,male,18.0,0,0,8.0500,S,Third,man,True,None,Southampton,True,True
3,49,0,3,female,18.0,1,0,17.8000,S,Third,woman,False,None,Southampton,False,False
4,371,0,3,male,18.0,1,0,6.4958,S,Third,man,True,None,Southampton,False,False
5,175,0,3,male,18.0,1,1,7.8542,S,Third,man,True,None,Southampton,False,False
6,385,0,2,male,18.0,0,0,73.5000,S,Second,man,True,None,Southampton,False,True
7,38,0,3,female,18.0,2,0,18.0000,S,Third,woman,False,None,Southampton,False,False
8,311,1,1,female,18.0,2,2,262.3750,C,First,woman,False,B,Cherbourg,True,False
9,417,1,2,female,18.0,0,2,13.0000,S,Second,woman,False,None,Southampton,True,False

In [41]:
%%duckdb

CREATE OR REPLACE MACRO get_stories() AS TABLE SELECT * from 's3://tt-bootcamp-shared/hackernews.parquet' where type = 'story';

select * from get_stories() limit 3

,id,deleted,type,by,time,text,dead,parent,poll,kids,url,score,title,parts,descendants
0,344066,False,story,acangiano,2008-10-26 05:07:59,None,False,<NA>,<NA>,"[344111, 344202, 344329, 344606]",http://antoniocangiano.com/2008/10/26/what-arc...,33,What Arc should learn from Ruby,[],10
1,344070,False,story,nickb,2008-10-26 05:17:05,None,False,<NA>,<NA>,[],http://www.cs.cmu.edu/~zhuxj/astro/html/spectr...,1,How to make your own spectrometer from a CD an...,[],0
2,344071,False,story,Ladarius11,2008-10-26 05:21:03,New free samples and free stuff added daily. O...,True,<NA>,<NA>,[],http://www.freestufffriend.com,1,Free Samples : Free Stuff : Freebies,[],-1

In [43]:
%%duckdb

select distinct embark_town from 's3://tt-bootcamp-shared/titanic.csv' 
limit 10

   embark_town
0    Cherbourg
1   Queenstown
2         None
3  Southampton

In [48]:
%%duckdb

select * EXCLUDE(rn,column00) from
(select *, row_number() over(partition by embark_town order by fare desc) as rn
from 's3://tt-bootcamp-shared/titanic.csv') where rn <= 3

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,1,1,female,23.0,3,2,263.0000,S,First,woman,False,C,Southampton,True,False
1,1,1,female,24.0,3,2,263.0000,S,First,woman,False,C,Southampton,True,False
2,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,False,False
3,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,True,False
4,1,1,female,35.0,0,0,512.3292,C,First,woman,False,None,Cherbourg,True,True
5,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,True,True
6,1,1,female,33.0,1,0,90.0000,Q,First,woman,False,C,Queenstown,True,False
7,0,1,male,44.0,2,0,90.0000,Q,First,man,True,C,Queenstown,False,False
8,0,3,male,4.0,4,1,29.1250,Q,Third,child,False,None,Queenstown,False,False
9,1,1,female,38.0,0,0,80.0000,None,First,woman,False,B,None,True,True
10,1,1,female,62.0,0,0,80.0000,None,First,woman,False,B,None,True,True

In [52]:
%%duckdb

select *, row_number() over(partition by embark_town order by fare desc) as rn
from 's3://tt-bootcamp-shared/titanic.csv' 
QUALIFY rn = 1

,column00,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,rn
0,88,1,1,female,23.0,3,2,263.0000,S,First,woman,False,C,Southampton,True,False,1
1,679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,True,False,1
2,412,1,1,female,33.0,1,0,90.0000,Q,First,woman,False,C,Queenstown,True,False,1
3,61,1,1,female,38.0,0,0,80.0000,None,First,woman,False,B,None,True,True,1

In [57]:
%%duckdb

select *, sum(pc) over(partition by VendorID, pickup_date order by tpep_pickup_datetime) as cum_pc
from
(select VendorID,cast(tpep_pickup_datetime as date) as pickup_date,tpep_pickup_datetime,passenger_count as pc 
from 's3://tt-bootcamp-shared/nyc-taxi-trip/yellow-taxi-data/*.parquet' )
limit 10

   VendorID pickup_date tpep_pickup_datetime  pc  cum_pc
0         1  2025-01-01  2025-01-01 00:00:00   1     1.0
1         1  2025-01-01  2025-01-01 00:00:03   2     3.0
2         1  2025-01-01  2025-01-01 00:00:17   1     4.0
3         1  2025-01-01  2025-01-01 00:00:31   1     5.0
4         1  2025-01-01  2025-01-01 00:00:35   1     6.0
5         1  2025-01-01  2025-01-01 00:01:06   1     7.0
6         1  2025-01-01  2025-01-01 00:01:28   4    11.0
7         1  2025-01-01  2025-01-01 00:01:44   0    12.0
8         1  2025-01-01  2025-01-01 00:01:44   1    12.0
9         1  2025-01-01  2025-01-01 00:01:53   1    13.0

In [80]:
%%duckdb


select time, type, avg(has_ai) over(order by time rows between 100 preceding and 100 following) ma_ai_has from
(select time, type, cast( (case when text is null then '' else text end like '% AI %') as int) as has_ai, text  
from 's3://tt-bootcamp-shared/hackernews.parquet' )
order by 1 desc
limit 10

                 time     type  ma_ai_has
0 2020-01-09 18:06:44  comment   0.009901
1 2020-01-09 18:06:39  comment   0.009804
2 2020-01-09 18:06:29    story   0.009709
3 2020-01-09 18:06:26  comment   0.009615
4 2020-01-09 18:06:24    story   0.009524
5 2020-01-09 18:06:12  comment   0.009434
6 2020-01-09 18:06:11  comment   0.009346
7 2020-01-09 18:06:05  comment   0.009259
8 2020-01-09 18:06:04  comment   0.009174
9 2020-01-09 18:06:02  comment   0.009091

In [81]:
%%duckdb


select time, type, avg(has_ai) over(order by time range between INTERVAL 180 DAYS preceding and INTERVAL 180 DAYS following) ma_ai_has from
(select time, type, cast( (case when text is null then '' else text end like '% AI %') as int) as has_ai, text  
from 's3://tt-bootcamp-shared/hackernews.parquet' )
order by 1 desc
limit 10

                 time     type  ma_ai_has
0 2020-01-09 18:06:44  comment   0.004939
1 2020-01-09 18:06:39  comment   0.004939
2 2020-01-09 18:06:29    story   0.004939
3 2020-01-09 18:06:26  comment   0.004939
4 2020-01-09 18:06:24    story   0.004939
5 2020-01-09 18:06:12  comment   0.004939
6 2020-01-09 18:06:11  comment   0.004939
7 2020-01-09 18:06:05  comment   0.004939
8 2020-01-09 18:06:04  comment   0.004939
9 2020-01-09 18:06:02  comment   0.004939

In [82]:
%%duckdb

select * from 's3://tt-bootcamp-shared/nyc-taxi-trip/yellow-taxi-data/*.parquet'
limit 10

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,2,2024-10-01 00:30:44,2024-10-01 00:48:26,1,3.00,1,N,162,246,1,18.4,1.0,0.5,1.50,0.0,1.0,24.90,2.5,0.0
1,1,2024-10-01 00:12:20,2024-10-01 00:25:25,1,2.20,1,N,48,236,1,14.2,3.5,0.5,3.80,0.0,1.0,23.00,2.5,0.0
2,1,2024-10-01 00:04:46,2024-10-01 00:13:52,1,2.70,1,N,142,24,1,13.5,3.5,0.5,3.70,0.0,1.0,22.20,2.5,0.0
3,1,2024-10-01 00:12:10,2024-10-01 00:23:01,1,3.10,1,N,233,75,1,14.2,3.5,0.5,2.00,0.0,1.0,21.20,2.5,0.0
4,1,2024-10-01 00:30:22,2024-10-01 00:30:39,1,0.00,1,N,262,262,3,3.0,3.5,0.5,0.00,0.0,1.0,8.00,2.5,0.0
5,2,2024-10-01 00:31:20,2024-10-01 00:36:00,2,0.97,1,N,137,137,1,7.2,1.0,0.5,2.44,0.0,1.0,14.64,2.5,0.0
6,1,2024-10-01 00:42:57,2024-10-01 00:49:01,1,1.30,1,N,142,48,1,7.9,3.5,0.5,2.55,0.0,1.0,15.45,2.5,0.0
7,1,2024-10-01 00:59:55,2024-10-01 01:02:24,1,0.50,1,N,230,161,1,5.1,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0
8,1,2024-10-01 00:00:47,2024-10-01 00:04:22,0,1.10,1,N,142,237,1,7.2,3.5,0.5,3.00,0.0,1.0,15.20,2.5,0.0
9,1,2024-10-01 00:17:36,2024-10-01 00:26:22,1,2.20,1,N,162,145,1,11.4,3.5,0.5,3.30,0.0,1.0,19.70,2.5,0.0

In [16]:
%%duckdb

select * from 
(select *, lead(ss,1) over(partition by bikeid order by starttime) as next_trip_ss,
lead(starttime,1) over(partition by bikeid order by starttime) as next_trip_starttime
from 
(select bikeid, starttime,"start station id" as ss, "end station id" es 
from 's3://tt-bootcamp-shared/nyc-bike-trip/201601.parquet') )  where next_trip_ss != es order by 1

,bikeid,starttime,ss,es,next_trip_ss,next_trip_starttime
0,14529,1/1/2016 21:20:29,444,453,470,1/10/2016 09:23:01
1,14529,1/14/2016 20:31:11,293,511,432,1/15/2016 09:13:52
2,14529,1/19/2016 18:12:16,442,238,453,1/2/2016 10:42:24
3,14529,1/2/2016 17:59:22,347,276,238,1/20/2016 08:43:27
4,14529,1/27/2016 18:36:28,345,79,312,1/28/2016 07:17:20
...,...,...,...,...,...,...
33719,24769,1/27/2016 07:21:28,490,520,469,1/27/2016 15:08:33
33720,24769,1/29/2016 07:55:09,3141,385,2004,1/3/2016 17:34:21
33721,24769,1/3/2016 21:25:07,507,224,385,1/30/2016 04:59:30
33722,24769,1/30/2016 04:59:30,385,3223,224,1/4/2016 07:54:55
33723,24773,1/18/2016 17:53:52,362,445,432,1/19/2016 09:11:18

In [20]:
s3.ls('tt-bootcamp-shared/nyc-taxi-trip/zone-lookup')

['tt-bootcamp-shared/nyc-taxi-trip/zone-lookup/taxi_zone_lookup.parquet',
 'tt-bootcamp-shared/nyc-taxi-trip/zone-lookup/taxi_zone_lookup_coordinates.parquet']

In [31]:
%%duckdb

select  d1.Zone as pu_zone, d2.Zone as do_zone, avg(total_amount) ,max(total_amount), median(total_amount), count(1) as n
from 's3://tt-bootcamp-shared/nyc-taxi-trip/green-taxi-data/*.parquet' f
JOIN 's3://tt-bootcamp-shared/nyc-taxi-trip/zone-lookup/taxi_zone_lookup.parquet' d1 on(f.PULocationID = d1.LocationID)
JOIN 's3://tt-bootcamp-shared/nyc-taxi-trip/zone-lookup/taxi_zone_lookup.parquet' d2 on(f.DOLocationID = d2.LocationID)
group by 1,2
having count(1) > 10
order by 3 desc
limit 10

,pu_zone,do_zone,avg(total_amount),max(total_amount),median(total_amount),n
0,Jamaica,Newark Airport,196.207692,252.65,191.030,13
1,Brooklyn Heights,Outside of NYC,175.108824,961.00,116.490,17
2,East Harlem North,Newark Airport,163.926667,189.19,169.200,27
3,West Concourse,Outside of NYC,162.258835,1095.54,148.120,103
4,Park Slope,Outside of NYC,157.083462,383.00,159.780,26
5,Flushing Meadows-Corona Park,Outside of NYC,156.010070,802.50,140.665,284
6,Corona,Outside of NYC,155.461500,245.81,162.100,20
7,Downtown Brooklyn/MetroTech,Outside of NYC,150.576552,383.26,147.810,29
8,Brooklyn Heights,Newark Airport,150.220588,181.20,153.100,17
9,East Williamsburg,Outside of NYC,150.045667,386.00,128.130,30

In [23]:
%%duckdb

select * from 's3://tt-bootcamp-shared/nyc-taxi-trip/zone-lookup/taxi_zone_lookup.parquet' limit 10

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone
5           6  Staten Island  Arrochar/Fort Wadsworth    Boro Zone
6           7         Queens                  Astoria    Boro Zone
7           8         Queens             Astoria Park    Boro Zone
8           9         Queens               Auburndale    Boro Zone
9          10         Queens             Baisley Park    Boro Zone